### ISSUE TITLE
Prompt to reset database

### ISSUE THREAD

**Issue by adamshand** [iansinnott/prompta#19]
FYI, this is the first time in a while, but I just got the prompt about a corrupted database using chat.prompta.dev.

**Comment by iansinnott** [comment]
hey @adamshand , sorry about this. yes that's due to the latest PR which changed the way migrations are run. The database needed to be reset as a result. 

I was thinking about how to create a smooth migratoin path before next release, but I had spaced that the website is built off of master immediately.

Resetting the database should allow you to continue using the site, and then you can run `Attempt Restore DB` from the command menu to try to restore past data.

**Comment by adamshand** [comment]
All good, was just worried it was the old bug coming back!
