### ISSUE TITLE
Mac build broken in github actions

### ISSUE THREAD

**Issue by g3mino** [iansinnott/prompta#49]
Hi,
Love this app - for me it's simply the best client I can run on an Intel Mac!

Not sure if there's an easier way to run this latest release on an Intel Mac, but:
- can't run it in a VM after installing DEB package on Debian Bookworm - missing deprectated libssl.so.1.1 librabry 
"prompta: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory"
- no mac package available
- don't like appimage, but will try nevertheless until other options are available?
- perhaps it would be easier to release it as a docker image also?

**Comment by iansinnott** [comment]
Thanks for the heads up and for the kind words. The github actions mac build is broken. This happened, as far as I know, due to some change github made in their app runners.

Just in case you weren't aware prompta also runs in the browser: [https://chat.prompta.dev/](https://chat.prompta.dev/).

Regarding the Docker image, you're referring to running the UI via web server, similar to the app linked to above? There is already a Dockerfile for running the sync server, but i'm guessing that's not what you're talking about.

**Comment by iansinnott** [comment]
Looking at the error logs its something in the rust build, which is surprising because Prompta doesn't do anything with the Rust side of Tauri. Maybe its time to migrate to Tauri 2.0.

Error in question: [https://github.com/iansinnott/prompta/actions/runs/11182023000/job/31087339186#step:10:864](https://github.com/iansinnott/prompta/actions/runs/11182023000/job/31087339186#step:10:864)

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

Looks like upgrading tauri may resolve the error.

**Comment by unfixa1** [comment]
The build problems in GitHub Actions for applications running on Intel Macs are mainly due to the lack of libssl.so.1.1 library, and there is no Mac package available.
You can use the tool [servbay](servbay.com) to set up a development environment to troubleshoot environment bugs

**Comment by iansinnott** [comment]
fixed in tauri v2, although i haven't tried out any of the builds other than arm mac
